fruits=[]
fruitName=input("enter fruit name:")
fruits.append(fruitName)
fruitName=input("enter fruit name:")
fruits.append(fruitName)
fruitName=input("enter fruit name:")
fruits.append(fruitName)
fruitName=input("enter fruit name:")
fruits.append(fruitName)
fruitName=input("enter fruit name:")
fruits.append(fruitName)
fruitName=input("enter fruit name:")
fruits.append(fruitName)
fruitName=input("enter fruit name:")
fruits.append(fruitName)
print(fruits)