marks=[]
std1=input("enter marks:")
marks.append(std1)
std2=input("enter marks:")
marks.append(std2)
std3=input("enter marks:")
marks.append(std3)
std4=input("enter marks:")
marks.append(std4)
std5=input("enter marks:")
marks.append(std5)
std6=input("enter marks:")
marks.append(std6)
marks.sort()
print(marks)
